app_port: "80"
app_tag: "latest"

datadog_checks:
  http_check:
    instances:
      - name: http_check_{{ inventory_hostname }}
        url: http://localhost:{{ app_port }}
        timeout: 15
        min_collection_interval: 30

                         
