name: CI/CD Workflow

on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  run-tests:
    if: |
      startsWith(github.ref, 'refs/heads/feature/') || 
      startsWith(github.ref, 'refs/heads/hotfix/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: echo "Tests done!!!"

  build-and-push:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Set up environment variables
      run: |
        echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> app/.env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> app/.env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> app/.env
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> app/.env
        echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> app/.env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> app/.env

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set sanitized branch name
      run: echo "BRANCH_NAME=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

    - name: Set short commit hash
      run: echo "SHORT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and Push Image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: .
        file: Dockerfile.production
        tags: |
          ruslan0688/vtiger-devops-app:${{ env.BRANCH_NAME }}-latest
          ruslan0688/vtiger-devops-app:${{ env.BRANCH_NAME }}-${{ env.SHORT_HASH }}